version: '3'

services:

  frontend:
    image: fitbit-ranking-webapp
    container_name: fitbit-ranking-frontend
    ports:
      - 3000:80
    depends_on:
      - backend

  backend:
    image: fitbit-ranking-backend
    container_name: fitbit-ranking-backend
    depends_on:
      - db
    links:
      - db
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  db:
    image: postgres
    container_name: database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: